![rmotr](https://user-images.githubusercontent.com/7065401/52071918-bda15380-2562-11e9-828c-7f95297e4a82.png)
<hr style="margin-bottom: 40px;">

# Pandas Series exercises

In [1]:
# Import the numpy package under the name np
import numpy as np

# Import the pandas package under the name pd
import pandas as pd

# Print the pandas version and the configuration
print(pd.__version__)

2.2.2

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Series creation

### Create an empty pandas Series

In [3]:
# your code goes here
s = pd.Series(['a', 1, 'b', 815])
print(s)

0      a
1      1
2      b
3    815
dtype: object

In [ ]:
pd.Series()

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X python list convert it to an Y pandas Series

In [7]:
# your code goes here
X = list([1, 2, 3, 4])
s = pd.Series(X)
print(s, type(s))

0    1
1    2
2    3
3    4
dtype: int64 <class 'pandas.core.series.Series'>

In [8]:
X = ['A','B','C']
print(X, type(X))

Y = pd.Series(X)
print(Y, type(Y)) # different type

['A', 'B', 'C'] <class 'list'>
0    A
1    B
2    C
dtype: object <class 'pandas.core.series.Series'>

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, name it 'My letters'

In [9]:
# your code goes here
X = pd.Series(np.arange(10))
X.name = "My letters"
X

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
Name: My letters, dtype: int64

In [ ]:
X = pd.Series(['A','B','C'])

X.name = 'My letters'
X

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, show its values

In [15]:
# your code goes here
X = pd.Series(np.arange(10), dtype=float)
X.values, X.dtype

(array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]), dtype('float64'))

In [16]:
X = pd.Series(['A','B','C'])

X.values

array(['A', 'B', 'C'], dtype=object)

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Series indexation

### Assign index names to the given X pandas Series

In [18]:
# your code goes here
X = pd.Series(np.arange(10), dtype=float)
X.index = np.arange(10, 20)
X

10    0.0
11    1.0
12    2.0
13    3.0
14    4.0
15    5.0
16    6.0
17    7.0
18    8.0
19    9.0
dtype: float64

In [19]:
X = pd.Series(['A','B','C'])
index_names = ['first', 'second', 'third']

X.index = index_names
X

first     A
second    B
third     C
dtype: object

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, show its first element

In [20]:
# your code goes here
X = pd.Series(np.arange(10), dtype=float)
X[0]

np.float64(0.0)

In [21]:
X = pd.Series(['A','B','C'], index=['first', 'second', 'third'])

#X[0] # by position
#X.iloc[0] # by position
X['first'] # by index

'A'

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, show its last element

In [28]:
# your code goes here
X = pd.Series(np.arange(10), dtype=float)
X.iloc[-1]

np.float64(9.0)

In [27]:
X = pd.Series(['A','B','C'], index=['first', 'second', 'third'])

X[-1] # by position
#X.iloc[-1] # by position
#X['third'] # by index

/tmp/ipykernel_6568/3915021251.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  X[-1] # by position

'C'

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, show all middle elements

In [33]:
# your code goes here
X = pd.Series(np.arange(10), dtype=float)
X.iloc[1:-1]

1    1.0
2    2.0
3    3.0
4    4.0
5    5.0
6    6.0
7    7.0
8    8.0
dtype: float64

In [31]:
X = pd.Series(['A','B','C','D','E'],
              index=['first','second','third','forth','fifth'])

#X[['second', 'third', 'forth']]
#X.iloc[1:-1] # by position
X[1:-1] # by position

second    B
third     C
forth     D
dtype: object

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, show the elements in reverse position

In [36]:
# your code goes here
X = pd.Series(np.arange(10), dtype=float)
X.iloc[::-1]

9    9.0
8    8.0
7    7.0
6    6.0
5    5.0
4    4.0
3    3.0
2    2.0
1    1.0
0    0.0
dtype: float64

In [35]:
X = pd.Series(['A','B','C','D','E'],
              index=['first','second','third','forth','fifth'])

#X.iloc[::-1]
X[::-1]

fifth     E
forth     D
third     C
second    B
first     A
dtype: object

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, show the first and last elements

In [41]:
# your code goes here
X = pd.Series(np.arange(10), dtype=float)
X.iloc[[0,-1]]

0    0.0
9    9.0
dtype: float64

In [42]:
X = pd.Series(['A','B','C','D','E'],
              index=['first','second','third','forth','fifth'])

#X[['first', 'fifth']]
#X.iloc[[0, -1]]
X[[0, -1]]

/tmp/ipykernel_6568/1500303121.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  X[[0, -1]]

first    A
fifth    E
dtype: object

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Series manipulation

### Convert the given integer pandas Series to float

In [50]:
# your code goes here
import numpy as np
X = pd.Series(np.arange(10), dtype=int)
y = pd.Series(X, dtype=np.float32)
y
y.dtype

dtype('float32')

In [45]:
X = pd.Series([1,2,3,4,5],
              index=['first','second','third','forth','fifth'])

pd.Series(X, dtype=np.float32)

first     1.0
second    2.0
third     3.0
forth     4.0
fifth     5.0
dtype: float32

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Reverse the given pandas Series (first element becomes last)

In [51]:
# your code goes here
X = pd.Series(np.arange(10), dtype=float)
y = X[::-1]
y

9    9.0
8    8.0
7    7.0
6    6.0
5    5.0
4    4.0
3    3.0
2    2.0
1    1.0
0    0.0
dtype: float64

In [52]:
X = pd.Series([1,2,3,4,5],
              index=['first','second','third','forth','fifth'])

X[::-1]

fifth     5
forth     4
third     3
second    2
first     1
dtype: int64

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Order (sort) the given pandas Series

In [56]:
# your code goes here
X = pd.Series(np.arange(10), dtype=float)[::-1]
X = X.sort_values()
X

0    0.0
1    1.0
2    2.0
3    3.0
4    4.0
5    5.0
6    6.0
7    7.0
8    8.0
9    9.0
dtype: float64

In [57]:
X = pd.Series([4,2,5,1,3],
              index=['forth','second','fifth','first','third'])

X = X.sort_values()
X

first     1
second    2
third     3
forth     4
fifth     5
dtype: int64

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, set the fifth element equal to 10

In [58]:
# your code goes here
X = pd.Series(np.arange(10), dtype=float)
X.iloc[4] = 10
X

0     0.0
1     1.0
2     2.0
3     3.0
4    10.0
5     5.0
6     6.0
7     7.0
8     8.0
9     9.0
dtype: float64

In [59]:
X = pd.Series([1,2,3,4,5],
              index=['A','B','C','D','E'])

X[4] = 10
X

/tmp/ipykernel_6568/4063770036.py:4: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  X[4] = 10

A     1
B     2
C     3
D     4
E    10
dtype: int64

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, change all the middle elements to 0

In [61]:
# your code goes here
X = pd.Series(np.arange(10), dtype=float)
X.iloc[1:-1] = 0
X

0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
5    0.0
6    0.0
7    0.0
8    0.0
9    9.0
dtype: float64

In [80]:
X[0:10]

0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
5    0.0
6    0.0
7    0.0
8    0.0
9    9.0
dtype: float64

In [81]:
X.iloc[-1]

np.float64(9.0)

In [82]:
X = pd.Series([1,2,3,4,5],
              index=['A','B','C','D','E'])

X[1:-1] = 0
X

A    1
B    0
C    0
D    0
E    5
dtype: int64

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, add 5 to every element

In [83]:
# your code goes here
X = pd.Series(np.arange(10), dtype=float)
X += 5
X

0     5.0
1     6.0
2     7.0
3     8.0
4     9.0
5    10.0
6    11.0
7    12.0
8    13.0
9    14.0
dtype: float64

In [84]:
X = pd.Series([1,2,3,4,5])

X + 5

0     6
1     7
2     8
3     9
4    10
dtype: int64

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Series boolean arrays (also called masks)

### Given the X pandas Series, make a mask showing negative elements

In [85]:
# your code goes here
X = pd.Series(np.arange(10), dtype=float) - 5
X < 0

0     True
1     True
2     True
3     True
4     True
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [86]:
X = pd.Series([-1,2,0,-4,5,6,0,0,-9,10])

mask = X <= 0
mask

0     True
1    False
2     True
3     True
4    False
5    False
6     True
7     True
8     True
9    False
dtype: bool

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, get the negative elements

In [87]:
# your code goes here
X = pd.Series(np.arange(10), dtype=float) - 5
X[X < 0]

0   -5.0
1   -4.0
2   -3.0
3   -2.0
4   -1.0
dtype: float64

In [88]:
X = pd.Series([-1,2,0,-4,5,6,0,0,-9,10])

mask = X <= 0
X[mask]

0   -1
2    0
3   -4
6    0
7    0
8   -9
dtype: int64

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, get numbers higher than 5

In [89]:
# your code goes here
X = pd.Series(np.arange(10), dtype=float)
X [X > 5]

6    6.0
7    7.0
8    8.0
9    9.0
dtype: float64

In [90]:
X = pd.Series([-1,2,0,-4,5,6,0,0,-9,10])

mask = X > 5
X[mask]

5     6
9    10
dtype: int64

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, get numbers higher than the elements mean

In [91]:
# your code goes here
X = pd.Series(np.arange(10), dtype=float)
X [X > X.mean()]

5    5.0
6    6.0
7    7.0
8    8.0
9    9.0
dtype: float64

In [92]:
X = pd.Series([-1,2,0,-4,5,6,0,0,-9,10])

mask = X > X.mean()
X[mask]

1     2
4     5
5     6
9    10
dtype: int64

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, get numbers equal to 2 or 10

In [97]:
# your code goes here
X = pd.Series(np.arange(10), dtype=float)
X[(X == 2) | (X == 10)]

2    2.0
dtype: float64

In [ ]:
X = pd.Series([-1,2,0,-4,5,6,0,0,-9,10])

mask = (X == 2) | (X == 10)
X[mask]

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Logic functions

### Given the X pandas Series, return True if none of its elements is zero

In [98]:
# your code goes here
X = pd.Series(np.arange(10), dtype=float)
X.all()

np.False_

In [99]:
X = pd.Series([-1,2,0,-4,5,6,0,0,-9,10])

X.all()

np.False_

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, return True if any of its elements is zero

In [100]:
# your code goes here
X = pd.Series(np.arange(10), dtype=float)
X.any()

np.True_

In [101]:
X = pd.Series([-1,2,0,-4,5,6,0,0,-9,10])

X.any()

np.True_

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Summary statistics

### Given the X pandas Series, show the sum of its elements

In [102]:
X = pd.Series(np.arange(10), dtype=float)
X.sum()

np.float64(45.0)

In [103]:
X = pd.Series([3,5,6,7,2,3,4,9,4])

#np.sum(X)
X.sum()

np.int64(43)

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, show the mean value of its elements

In [104]:
# your code goes here
X = pd.Series(np.arange(10), dtype=float)
X.mean()

np.float64(4.5)

In [105]:
X = pd.Series([1,2,0,4,5,6,0,0,9,10])

#np.mean(X)
X.mean()

np.float64(3.7)

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, show the max value of its elements

In [106]:
# your code goes here
X = pd.Series(np.arange(10), dtype=float)
X.max()

9.0

In [107]:
X = pd.Series([1,2,0,4,5,6,0,0,9,10])

#np.max(X)
X.max()

10

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)